GET http://localhost:8080/getUpdateMD5?deviceName=device00000
Accept: application/json

###

GET http://localhost:8080/getUpdateFile?deviceName=device00000
Accept: application/json

###
http://upgrade-mofahezi.xiaolimofahezi.com:8080/getUpdateFile?deviceName=device00004